// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBB4ITW4zjri__vX7xc_tSd5U6abnpzrI',
    appId: '1:202571349641:android:235d7f7954415cf3a31058',
    messagingSenderId: '202571349641',
    projectId: 'expense-tracker-91ff4',
    storageBucket: 'expense-tracker-91ff4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbLjcHrdFO8ouhUIKYE7fBJLpOXu4f7NU',
    appId: '1:202571349641:ios:3b1e641ac53251dca31058',
    messagingSenderId: '202571349641',
    projectId: 'expense-tracker-91ff4',
    storageBucket: 'expense-tracker-91ff4.firebasestorage.app',
    iosBundleId: 'com.expense.tracker.expenseTracker',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBB4ITW4zjri__vX7xc_tSd5U6abnpzrI',
    appId: '1:202571349641:web:0dabf9e8e41c5a77a31058',
    messagingSenderId: '202571349641',
    projectId: 'expense-tracker-91ff4',
    authDomain: 'expense-tracker-91ff4.firebaseapp.com',
    storageBucket: 'expense-tracker-91ff4.firebasestorage.app',
  );
}
